apps:
  api:
    port: 3000
    privatePort: 4000
    useCachingInterceptor: true
  cacheWarmer:
    port: 4001
  queueWorker:
    port: 4002
  transactionsProcessor:
    port: 4003
    maxLookBehind: 100
  eventsNotifier:
    url: 'amqp://user-622ad86c:<5d595182393339e3919b4a3b1f96dbe31fae1bb17f2629ccbcccbed89d3965fa>@devnet-rabbitmq.beaconx.app:5672/'
    port: 5672
    queue: 'events-622ad86c'
libs:
  common:
    network: ${NETWORK}
    urls:
      api: ${API_URL}
    database:
      host: 'localhost'
      port: 27017
      # username: 'root'
      # password: 'root'
      name: 'example'
      tlsAllowInvalidCertificates: true
    redis:
      host: '127.0.0.1'
      port: 6379
    nativeAuth:
      # maxExpirySeconds:
      acceptedOrigins:
        - https://utils.multiversx.com
        - devnet-rabbitmq.beaconx.app
    security:
      admins: []
    # rateLimiterSecret:
